Section A: Data Structures & Control Structures

1.	Create a list of 5 integers. Perform and print the result of the following operations: append, extend, insert, remove, pop, clear, index, count, sort, and reverse.

In [1]:
list=[4,6,9,5,7]
list.append(10)
print("appending:",list)
list.extend([2,3])
print("extending:",list)
list.insert(2,18)
print("inserting:",list)
list.remove(10)
print("removing:",list)
list.pop(2)
print("poping:",list)
list.index(7)
print("indexing:",list)
list.count(3)
print("counting:",list)
list.sort()
print("sorting:",list)
list.reverse()
print("reverse:",list)
list.clear()
print("clearing:",list)

appending: [4, 6, 9, 5, 7, 10]
extending: [4, 6, 9, 5, 7, 10, 2, 3]
inserting: [4, 6, 18, 9, 5, 7, 10, 2, 3]
removing: [4, 6, 18, 9, 5, 7, 2, 3]
poping: [4, 6, 9, 5, 7, 2, 3]
indexing: [4, 6, 9, 5, 7, 2, 3]
counting: [4, 6, 9, 5, 7, 2, 3]
sorting: [2, 3, 4, 5, 6, 7, 9]
reverse: [9, 7, 6, 5, 4, 3, 2]
clearing: []


2.Create a tuple that stores 3 student names. Try changing the second name in the tuple. What happens? Explain why.

In [2]:
tuple1=("sami","nee","giri")
# Tuples are immutable, which means that once a tuple is created, its elements cannot be changed or modified
#If you need to modify the contents of a tuple, you would have to create a new tuple with the desired changes.
#otherwise change tuple to list then we can modify
tuple2=("sami","neeli","giri")
tuple1=tuple2

3.Create a set of integers with some duplicate values. Print the set and explain the output.

In [3]:
integers={1,3,2,5,3,6,8,2,4,6,7}
print("set:",integers)
#Set only allow unique value
#Its remove duplicates automatically
#Sets are unordered, so the numbers may appear in any order when printed

set: {1, 2, 3, 4, 5, 6, 7, 8}


4.Create a dictionary with the keys: 'name', 'age', and 'city'. Update the age and add a new key 'email'. Print the final dictionary.

In [4]:
dic={'name':'sami','age':20,'city':'tichy'}
dic['age']= 21
dic['email']='abc@gmail.com'
print('final dictionary:',dic)


final dictionary: {'name': 'sami', 'age': 21, 'city': 'tichy', 'email': 'abc@gmail.com'}


5.Write a script that checks if a person is eligible to vote (age ≥ 18). Take age as a variable and print the appropriate message

In [5]:
def vote_eligible():
    age=int(input("Enter your age :"))
    if age>=18:
        print("Your are eligible for voting")
    else:
        print("Your are not eligible for voting")

vote_eligible()

Enter your age : 17


Your are not eligible for voting


In [6]:

def grade(marks):
    if marks>=90:
        return "A"
    elif marks>=75 and marks<=89:
        return "B"
    elif marks>=50 and marks<=74:
        return "C"
    return "Fail"

grade(98)

'A'

7.Given a number, check if it's positive, and if it is also even. If not positive, print if it's zero or negative.

In [7]:
def check(num):
    if num>0 and num%2==0:
        print(num,"is positive and even")
    elif num<0 and num%2==0:
        print(num,"is negative and even")
    elif num<0 and num%2!=0:
        print(num,"is negative and odd")
    elif num>0 and num%2!=0:
        print(num,"is positive and odd")
    elif num==0:
        print(num,"is zero")

check(23)
    
    
        

23 is positive and odd


Section B: Numpy

In [8]:
import numpy as np

scalar=np.array(5)
print(scalar)

arr1=np.array([1,5,3,7,8,9])
print(arr1)

arr2=np.array([[2,4,6],[7,9,5]])
print(arr2)

5
[1 5 3 7 8 9]
[[2 4 6]
 [7 9 5]]


In [9]:
arr=np.random.randint(0,100,(4,4))
print(arr)

[[12 88 62 18]
 [64 96 57  1]
 [63 14 78 54]
 [61 52 21 91]]


In [10]:
import pandas as pd
num=np.random.randint(0,100,(3,3))
df=pd.DataFrame(num,columns=['A','B','C'])
print(df)


    A   B   C
0  75  86  61
1  62  39  56
2  38  33   8


Section C: Exploring Pandas

In [16]:
data={'Name' : ['sami','giri','prasanth','neeli','easwaran','dinesh','vinoth','thina','naveen','veera'],
      'Age': [20,21,21,20,21,20,21,22,22,21],
      'City': ['trichy','trichy','perambalur','trichy','kadalur','sivagangai','tricy','thanjaur','chennai','rameshwarm'],
      'Salary': [1000000,400000,43000,50000,90000,None,200000,43000,54000,83000]}
dataf=pd.DataFrame(data)
dataf

,Name,Age,City,Salary
0,sami,20,trichy,1000000.0
1,giri,21,trichy,400000.0
2,prasanth,21,perambalur,43000.0
3,neeli,20,trichy,50000.0
4,easwaran,21,kadalur,90000.0
5,dinesh,20,sivagangai,NaN
6,vinoth,21,tricy,200000.0
7,thina,22,thanjaur,43000.0
8,naveen,22,chennai,54000.0
9,veera,21,rameshwarm,83000.0


In [17]:
dataf.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   Name    10 non-null     object 
 1   Age     10 non-null     int64  
 2   City    10 non-null     object 
 3   Salary  9 non-null      float64
dtypes: float64(1), int64(1), object(2)
memory usage: 452.0+ bytes


In [18]:
dataf.describe()

,Age,Salary
count,10.000000,9.000000
mean,20.900000,218111.111111
std,0.737865,315426.474969
min,20.000000,43000.000000
25%,20.250000,50000.000000
50%,21.000000,83000.000000
75%,21.000000,200000.000000
max,22.000000,1000000.000000


In [19]:
dataf.drop('City' ,axis=1, inplace=True)

print(dsf)

       Name  Age          Salary
0      sami   20  1000000.000000
1      giri   21   400000.000000
2  prasanth   21    43000.000000
3     neeli   20    50000.000000
4  easwaran   21    90000.000000
5    dinesh   20   218111.111111
6    vinoth   21   200000.000000
7     thina   22    43000.000000
8    naveen   22    54000.000000
9     veera   21    83000.000000


In [21]:
dataf['Salary'].fillna(dsf['Salary'].mean())

0    1000000.000000
1     400000.000000
2      43000.000000
3      50000.000000
4      90000.000000
5     218111.111111
6     200000.000000
7      43000.000000
8      54000.000000
9      83000.000000
Name: Salary, dtype: float64

In [23]:
dataf.drop_duplicates(inplace=True)
dataf

,Name,Age,Salary
0,sami,20,1000000.000000
1,giri,21,400000.000000
2,prasanth,21,43000.000000
3,neeli,20,50000.000000
4,easwaran,21,90000.000000
5,dinesh,20,218111.111111
6,vinoth,21,200000.000000
7,thina,22,43000.000000
8,naveen,22,54000.000000
9,veera,21,83000.000000
